### ISSUE TITLE
support timer type annotation

### ISSUE THREAD

**Issue by dmuino** [Netflix/servo#145]
It would be convenient if we could support an annotation for timers around a method call.

``` java
@Time
int someExpensiveMethod() {
  // do something
  return 42;
}
```

The name for the monitor should default to the method name, but it should support a name attribute to override it. The default TimeUnit should be milliseconds, but it should support other TimeUnits.

We'll have to intercept the method call using something similar to https://code.google.com/p/google-guice/wiki/AOP

**Comment by brharrington** [comment]
Refile for [spectator](https://github.com/Netflix/spectator) if it is still needed.
