### ISSUE TITLE
un-final PollScheduler?

### ISSUE THREAD

**Issue by asilinskas** [Netflix/servo#188]
For my unit tests, I wanted to mock PollScheduler so that I can intercept and manually run PollRunnable objects that are scheduled. Since the PollScheduler class is final I can't mock it with EasyMock without bringing in a definalizer. I know I can start a PollScheduler with a mocked ScheduledExecutorService, but multiple tests are typically run in parallel so this won't work without a lot more complexity. Is there any chance of the final keyword being removed from the PollScheduler class declaration?

**Comment by brharrington** [comment]
It sounds like there is a workaround, closing for now.
