### ISSUE TITLE
document simple best practice usage of servo

### ISSUE THREAD

**Issue by brharrington** [Netflix/servo#218]
It would be useful to come up with best practices for how to use servo and maybe deprecate some of the options that are mostly historical. In particular we seem to get a lot of questions around:
- Handling of interaction with registry.
- Appropriate use and granularity of monitors vs logs.
- Debugging an explosion of metrics, and possibly supporting some scheme for automated rollup on the observer to prevent overwhelming a backend.

**Comment by nohros** [comment]
Usage of BucketTimer could he added to the list?

**Comment by brharrington** [comment]
We have invested in [spectator docs](http://netflix.github.io/spectator/en/latest/), servo is not receiving significant improvements at this time and our documentation bandwidth will be going to Spectator/Atlas.
