### ISSUE TITLE
Min/Max Gauge as part of BucketTimer should be initialized before polling

### ISSUE THREAD

**Issue by FullGC** [Netflix/servo#227]
Hi,
according to the 'reademe' document, BucketTimer should behave as follows:

"Assuming in the above code that the getRecommendations() method was called 7 times, and the values reported were: 49ms, 40ms, 400ms, 50ms, 500ms, 2000ms, 501ms. The following metrics would be available:
name=getRecommendations statistic=totalTime (49 + 40 + 400 + 50 + 500 + 2000) value=3039
name=getRecommendations statistic=min value=40
name=getRecommendations statistic=max value=2000"

It should be working well when sending raw stats, but when updating stats as Rates, as I figure, the Min/Max gauges should be initialized before every observer update (before every poll). 
Otherwise their value does not reflect the min/max time for the last minute, but from the monitor creation date. 
CounterToRateMetricTransform handles only Counter type, and its reasonable, but should handle Min/Max gauges as well, as they are updated in a method call, just like Counters.
So back to the above example. assuming that in the last observer update the Min value was 10, the next call (after the update ) to getRecommendations()  will leave the Min value on 10, even though the Min time that the API last in the last minute(or other polling unit-time) was 40.
Thanks!

**Comment by alexhilman** [comment]
Hello,

I am encountering the same seemingly strange (or unexpected values) when publishing metrics.

There seems to be a discrepancy (or at least a point of confusion) between the documentation and the results when referring to Timer's statistics of `count` and `totalTime`.

The wiki says the following about a `BasicTimer`:
> A `BasicTimer` is a composite monitor that generates four metrics per polling interval:
> ...
> * The total time recorded. `statistic=totalTime`
> * The number of times the event has been recorded. `statistic=count`

As it is referring to metrics I assume it means generation of `com.netflix.servo.Metric` objects. Furthermore the listed example on the wiki is stated as such:
> Assuming doSomething() was called twice and the recorded times were 5ms and 15ms the following metrics will be generated:
>
> name=doSomething statistic=totalTime value=20
> name=doSomething statistic=count value=2

When testing these statistics directly on the `BasicTimer` instance the values are as expected (`totalTime` = 20 and `count` = 2). However when gathering the metrics on a polling schedule the metrics are _not_ as expected and they don't line up with the documentation I have found. The values in the `Metric` updates are `totalTime` = 0.333333333 and `count` = 0.033333333.

Just an FYI - this issue caused some headaches.
