### ISSUE TITLE
Variable CompositeMonitors and JMX registry

### ISSUE THREAD

**Issue by ryanrupp** [Netflix/servo#253]
The JMX monitor registry doesn't work well with CompositeMonitors where the number of sub monitors is dynamic and can change during runtime after registration. This is because the JMX monitor registry only registers the sub monitors that are present when the composite monitor is being registered. Any additions or removals will not be reflected via JMX. Some ideas on how to fix this:

1) Change the areas such as DynamicTimer and DynamicCounter to just be standard monitors (not composite) and then have those utility classes handle the registering/unregistering with the monitor registry of individual monitors for each timer/counter used. Not sure how this would affect publishing of the metrics though offhand. Also could consider a guideline that CompositeMonitors should have all sub monitors defined at the point of creation but not sure how others are using this.
2) Change the JMX registry to do some sort of polling on CompositeMonitors to check for changes. This would probably have to store the state of each CompositeMonitor from the last time it polled and see what was added/removed and modify the mbeans accordingly.

Curious what others think. I have the changes for DynamicTimer for the first approach I mentioned here but then thought maybe it makes more sense to go to the root of the issue (which is the JMX registry not supporting variable CompositeMonitors).

**Comment by bcoughlan** [comment]
@ryanrupp For the first approach, are you just doing registering each timer when it is created?

**Comment by ryanrupp** [comment]
Yeah, I probably should've linked the code change for this, forgot I pushed it up to my fork, here it is but it's out of date at this point -https://github.com/ryanrupp/servo/commit/cf7553b9ef575b821535f44a408af926d5a4ecda

Main changes were:

1) DynamicTimer/Counter are no longer CompositeMonitors (since it won't work with JMX well)
2) The ExpiringCache has a getter function for when a map cache miss occurs and it has to create a new object. During this time it creates the timer/counter and then registers it with the registry.
3) ExpiringCache had to be modified so we can run a function when eviction from the cache occurs, did this so the timer/counter can then be unregistered from the registry upon expiration.
