### ISSUE TITLE
please document how servo communicates with a backend

### ISSUE THREAD

**Issue by mooreb** [Netflix/servo#257]
Hi there,

I'd like to reuse servo but am having trouble understanding how servo, as an open-source entity, communicates with a backend, any backend, for data collection, retention, display/graphing, aggregation, slicing (by servo-supported dimensions), etc. Is any servo-supported back-end open-sourced? How do the metrics get from servo to something that can display them? Can all of this be publicly documented?

Thanks much in advance,

b

**Comment by brharrington** [comment]
See #143.
