### ISSUE TITLE
BaseMetricObserver.updateImpl shouldn't be public

### ISSUE THREAD

**Issue by sslavic** [Netflix/servo#308]
If I understood well the purpose of BaseMetricObserver.updateImpl method, it should not be public, since it's not meant to be called directly but through BaseMetricObserver.update method call.

https://github.com/Netflix/servo/blob/master/servo-core/src/main/java/com/netflix/servo/publish/BaseMetricObserver.java#L62

**Comment by brharrington** [comment]
Agreed in general, but it looks like there are some internal use-cases that rely on it being public at this time and we are not planning to change the public server APIs. In general for improvements will be focused on [spectator](http://netflix.github.io/spectator/en/latest/intro/servo-comparison/).
