### ISSUE TITLE
Performance issues when using DynamicCounter for 12K unique metrics incremented over 100K per second

### ISSUE THREAD

**Issue by gihad** [Netflix/servo#315]
Hey guys,

I'm replacing statsd java client with Servo to send metrics straight from an application to graphite. This would be running in more or less 20 servers sending data to a common graphite backend. Each of this servers increment metrics about 100K times per second.

I'm making generic versions of DynamicCounters to support different counters and even gauges. In my first test with BasicCounter being generated inside a DynamicCounter class, I'm experience issues where metrics being reported are lower than it should be, playing with the Async queue size and polling time makes it a bit better but still can't keep up.

I've profiled the application and I'm having trouble identifying the bottleneck. Have you guys seen this type of intense use case? I assume that the use case in Netflix has even more load. Any tips would be appreciated.

I will add more information here when I try to profile it again.

Thanks,
Gihad

**Comment by dmuino** [comment]
Our recommendation at Netflix is to avoid calling DynamicCounter.increment in a performance critical region. Every call involves a concurrent map lookup so it's very expensive. Your options are:

- Use a regular BasicCounter that you've registered. This is just an AtomicLong increment so it's very fast.

- Keep using a DynamicCounter but move the .increment() calls outside the critical loop, and at the end call increment(config, delta) where delta is a locally computed delta (using a regular Long / AtomicLong as needed).

**Comment by gihad** [comment]
Hey dmuino,

I'm considering a third option:

Adding data sampling ability to the framework with a configurable rate (e.g.: 1%~100%). Perhaps it could be added to the DynamicCounter as a configurable variable with a default value of 100%. If this value was set to 5%, only 1 of every 20 (uniform distribution) increment() calls would actually be executed. Before the metrics are published to a backend, they would have to be multiplied by the equivalent factor = (100/Sampling Rate). This form of data sampling is acceptable in my use case. 

Do you see any problems in terms of adding this to servo?

Thanks again,
Gihad

**Comment by dmuino** [comment]
Sorry for the late reply. This fell through the cracks. 

I'm not sure I understand your proposed implementation. If it's something new, like DynamicSamplingCounter.increment(...) where increment() returns immediately without doing any work 95% of the time (or a value that is the same for all sampled counters so no per-counter lookups need to happen), I think that would work for counters that get significant usage. I'm not sure of a reasonable implementation for DynamicCounter where we need to keep track of the % for each counter since that wouldn't give us any performance benefits.

Please feel free to submit a PR for this.

**Comment by brharrington** [comment]
File an issue for [spectator](https://github.com/Netflix/spectator/issues) if this is still something useful. In general we are not investing in improving servo at this time. Spectator performance is something we'll be investing in.

**Comment by gihad** [comment]
Thanks for the follow up! Back when this was posted I was trying to get around the single threaded/low performance nature of the [official statsd daemon](https://github.com/statsite/statsite) by moving that to the application level with servo. I ended up going another route by replacing the "default" statsd with a [fast c implementation](https://github.com/statsite/statsite).

**Comment by brharrington** [comment]
Good to know, thanks for providing the links.
