### ISSUE TITLE
Allow a Monitor to declare it's own output class and change MonitorMBean#createAttributeInfo to use it

### ISSUE THREAD

**Issue by jonfreedman** [Netflix/servo#320]
There's a really nice JMX dashboard available through a project called [hawtio](http://hawt.io) which can create an ticking graph based on numerical values exposed over JMX but this doesn't like `java.lang.Number`.  If the Monitor interface allowed a output class to be supplied then all Timer implementations could be exposed as `java.lang.Long`  MonitorMBean#createAttributeInfo could use that as the type value instead of using reflection and the hawtio charting will work out of the box.

**Comment by brharrington** [comment]
Do you know the rationale for not supporting number? Visual VM supports a similar feature and works fine on the values as current modeled. Is there some reason hawtio doesn't support arbitrary numbers?

**Comment by jonfreedman** [comment]
I'm not that familiar with hawtio, I just know that I fixed the issue with a patched MonitorMBean which used java.lang.Long intead of Number, I do want to dig into hawtio but not sure when I will get round to that
On 8 May 2015 11:49 pm, brharrington <notifications@github.com> wrote:Do you know the rationale for not supporting number? Visual VM supports a similar feature and works fine on the values as current modeled. Is there some reason hawtio doesn't support arbitrary numbers?
