### ISSUE TITLE
GraphiteExporter: monitors registered with an "id" are not properly exported

### ISSUE THREAD

**Issue by brenuart** [Netflix/servo#322]
The `GraphiteExporter`doesn't take the ìd` assigned to the monitor into account when exporting the corresponding metrics value.
Example: 

```
// A counter declared by annotation
@Monitor(name="mycounter1")
private AtomicInteger mycounter1 = new AtomicInteger();

// Another counter
private Counter mycounter2;

public MyConstrctor() {
   mycounter2 = Monitors.newCounter("mycounter2");
   Monitors.registerObject("InstanceId", this);
}
```

The `GraphiteExporter` won't consider the _id_ used when registering the monitors (_InstanceId_ in this example) - but only the monitor's _names_. So the produced metrics will be named:

```
mycounter1
mycounter2
```

instead of

```
InstanceId.mycounter1
InstanceId.mycounter2
```

This is causing overlaps when multiple instance of the instrumented/monitored object is created. This happens for `NFHttpClient.getConnectionsInPool()` for instance...

**Comment by brharrington** [comment]
The id should get used. I'm not that familiar with spring cloud, but they were on a pretty old version. Please try the latest release.
