### ISSUE TITLE
Wiki is not up to date

### ISSUE THREAD

**Issue by Ciruman** [Netflix/servo#347]
The issue is related to the wiki. The jmx part is not not up to date.

https://github.com/Netflix/servo/wiki

Currently is doing this:

```
private final Counter bytesSent = Monitors.newCounter("bytesSent");
```

and:

```
Monitors.registerObject(this);
```

Thanks,
Diego

I do not achive the goal to start the example:

https://github.com/Netflix/servo/tree/master/servo-example/src/main/java/com/netflix/servo/example

It runs(echo and exit are working), but it does not provide jmx(I can not connect with jconsole).

**Comment by brharrington** [comment]
I updated the gradle command in the examples section, but it sounds like you got it to run. I tried with jvisualvm and jmc and both are able to connect and show the entries in jmx.

<img width="1062" alt="screen shot 2015-08-25 at 8 39 50 am" src="https://cloud.githubusercontent.com/assets/1289028/9471393/ec452158-4b04-11e5-8402-e7a473f2d606.png">

Are you saying you cannot connect to jmx at all or that you aren't seeing the data in jmx?

**Comment by Ciruman** [comment]
Hi,
I think I was not clear because I talked about two things. 1)The documentation is not consistent with the example code and 2)I do not achieve to see the mbeans. Forget 2. I will try to explain 1 :-)

In the documentation(https://github.com/Netflix/servo/wiki#jmx), the metrics are initializated like this:

@Monitor(name="BytesIn", type=COUNTER)
private AtomicLong bytesIn = new AtomicLong(0L);

But in the example:

https://github.com/Netflix/servo/blob/master/servo-example/src/main/java/com/netflix/servo/example/BaseHandler.java

metrics are started like this:

private final Counter bytesReceived = Monitors.newCounter("bytesReceived");

I would expect to get the same code in the documentation. 

Thank you!

**Comment by brharrington** [comment]
Documentation and other improvement efforts are going to [spectator](https://github.com/Netflix/spectator). PRs welcome, but we have no plans to invest our limited resources improving the servo docs.
