### ISSUE TITLE
AwsInjectableTag: tag values are missing if instance-data hostname does not resolve

### ISSUE THREAD

**Issue by rattigan** [Netflix/servo#349]
`instance-data` is not always a resolvable host in ec2. The field `metadataUrl` inAwsInjectableTag  should be changed from:

```
http://instance-data/latest/meta-data
```

to 

```
http://169.254.169.254/latest/meta-data
```

as documented in http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

**Comment by brharrington** [comment]
For reference, here is the PR where it was changed to use instance-data: https://github.com/Netflix/servo/pull/229

@dmuino what is your opinion? It would be nice to document the choice clearly.

**Comment by brharrington** [comment]
No plans to change the behavior at this time.
