### ISSUE TITLE
New Storage Driver

### ISSUE THREAD

**Issue by rodionos** [Netflix/servo#355]
We'd like to develop a storage driver for the servo framework with support for [Axibase Time-Series Database](https://axibase.com/products/axibase-time-series-database/), both network protocol and HTTP/json. 

**TCP/UDP:**
http://axibase.com/atsd/api/#command:-series

```
series e:nurswgvml007 d:2015-09-05T12:30:00Z m:jmx.gc_time_percent=1.2 t:collector=MarkSweepCompact
```

**HTTP:**
http://axibase.com/atsd/api/#series:-insert

``` json
[
    {
        "entity": "nurswgvml007",
        "metric": "jmx.gc_time_percent",
        "tags": {"collector": "MarkSweepCompact"}
        "data": [
            {
                "d": "2015-09-05T12:30:00Z",
                "v": 1.2
            }
        ]
    }
]
```

The network protocol implementation is likely to be similar to Graphite, based on prior integrations. Is the framework open for such integration, merging PRs for new storage drivers into master? If that's the case, are there any guidelines that are recommended for storage driver implementations?

**Comment by dmuino** [comment]
We are actually trying to reduce the scope to only things we use internally. We don't use graphite at Netflix and the driver has many issues. People have been adding private bug fixes and enhancements to make it work for their setups. It's really hard for us to assess whether a given fix or enhancement introduces regressions or other problems. We would love it if someone were to volunteer to take over the graphite driver and improve it.

We were thinking that the best way to add support for new backends would be for the people using them to control them fully and we could just have a wiki page where we would point users to projects that implement sending servo metrics to different backends.

**Comment by brharrington** [comment]
I agree with Daniel we want to make sure there is vested interest from a maintainer about a given component so it will be supported well. One example of a separate, but related project is the stackdriver lib, though it hasn't had much activity since being setup:

https://github.com/StudyBlue/servo-stackdriver

The other option is we could look into setting up a contrib group so we could have some outside maintainers. I think the main question is what is the best way to support and build it up going forward. From a testing and maintenance perspective do we benefit from having it in the same repo? Do we want to have a separate repo so releases and other tasks could be done independently?

**Comment by rodionos** [comment]
> reduce the scope to only things we use internally.

Makes sense, and I'm glad I asked.

My understanding is that going forward: 

- servo framework will include only storage drivers used internally at Netflix 
- There will be a new repo for extended storage drivers, e.g. servo-drivers
- Current out-of-scope drivers such as Graphite will be moved to the new repo at some point of time.
- Server framework will have no dependencies to servo-drivers. There will be a link on servo readme.md to servo-drivers readme.md

Can you think of a way to make storage driver implementation in the servo framework extensible? For instance, similar to log appenders, where storage driver implementation is specified with class name in properties file.

    servo.storage.driver=com.axibase.atsd.drivers.servo.MetricObserver
    #servo.storage.driver=com.netflix.servo.publish.graphite.GraphiteMetricObserver

**Comment by brharrington** [comment]
[Spectator](https://github.com/Netflix/spectator) allows flexible registry implementations. We are not investing in improving servo.
