### ISSUE TITLE
Misleading BucketTimer Getting Started Wiki Doc

### ISSUE THREAD

**Issue by oliver-schoenherr** [Netflix/servo#374]
The Bucket Timer Getting Started Doc use a obsolete Version of the Bucket Config Builder.

https://github.com/Netflix/servo/wiki/Getting-Started#buckettimer

The doc should use ` new BucketConfig.Builder()` instead of `BucketConfig.builder()`

**Comment by brharrington** [comment]
The change has been made. Thanks for pointing out the error.
