### ISSUE TITLE
GraphiteMetricObserver with UDP support

### ISSUE THREAD

**Issue by masgari** [Netflix/servo#383]
Current `com.netflix.servo.publish.graphite.GraphiteMetricObserver` creates TCP socket internally, this can be modified to support UDP protocol. 

Something similar to https://github.com/dropwizard/metrics/blob/3.1-maintenance/metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteSender.java

**Comment by brharrington** [comment]
Thanks for the pointer. We don't actively use the Graphite observer at Netflix so it is unlikely we'll prioritize this issue on our side. We'll be happy to consider a PR that adds support for UDP though.
