### ISSUE TITLE
How to publish the metrics collected during the last incomplete interval?

### ISSUE THREAD

**Issue by hiteshdholaria** [Netflix/servo#396]
We are using **Netflix Servo v0.9.2** with below configuration.
No. of Pollers: **1**
Poller: **MonitorRegistryMetricPoller**
Poller Interval: **30 sec**

We are able to publish all the metrics collected during all the previous complete intervals (e.g., 30 sec), however it is not publishing the other metrics which were collected during the last incomplete interval (e.g., 20 sec).

We do not wish to wait (i.e., sleep the main thread) for the last interval to complete before we can publish those collected metrics in the last incomplete interval.

Can you help us manually publish those metrics collected in the last incomplete interval.

**Comment by brharrington** [comment]
We typically do it by configuring the system to use [ClockWithOffset](https://github.com/Netflix/servo/blob/master/servo-core/src/main/java/com/netflix/servo/util/ClockWithOffset.java). On shutdown it will trigger a regular update, set an offset of one step interval, and trigger another update. The main reason for adjusting the clock is that there are a number of things that depend on the time, such as rate conversions, and it is easier to ensure they are all behaving normally if they think it is actually past the next step boundary.

**Comment by hiteshdholaria** [comment]
Thanks @brharrington .
Does setting an offset of one step interval trigger another update or it has to be triggered manually?
Can you post the relevant code segment if it has to be triggered manually.

**Comment by hiteshdholaria** [comment]
Solved it finally! Thanks a lot, @brharrington.
