### ISSUE TITLE
MonitorTags annotation should be recognized from parent class

### ISSUE THREAD

**Issue by PavlikPolivka** [Netflix/servo#403]
Right now if I have MonitorTags annotated field in my parent class it's not registered by Monitors:getMonitorTags method.
It should go over all the parents and find annotated fields there.

Or is this intended behavior?

**Comment by dmuino** [comment]
I believe that was added for some backwards compatibility with an older system we had in place. Usage of annotations for metrics in our codebase has been deprecated in favor of explicit calls to create and register monitors, or usage of things like DynamicCounter/DynamicTimer. 

I don't have any objections to the functionality you suggest, so feel free to submit a PR to scan the hierarchy of classes.
