### ISSUE TITLE
PollScheduler maximum threads? Configurable?

### ISSUE THREAD

**Issue by bltb** [Netflix/servo#409]
Hi all!

What is the reason that the number of PollScheduler threads is equal to the number of cores?

https://github.com/Netflix/servo/blob/master/servo-core/src/main/java/com/netflix/servo/publish/PollScheduler.java#L66

Would anyone object if we made this maximum configurable?

Thanks!

**Comment by dmuino** [comment]
I think the idea was that would be the default. If you wanted something custom you'd use the method where you pass an explicit `ScheduledExecutorService` which you can configure it to suit your needs.

**Comment by bltb** [comment]
Thanks @dmuino . Implemented. :smile: I am now wondering how to calculate the optimal number of threads required to poll a certain number of metrics. I would presume if we have too few `PollScheduler` threads the metrics could be "stale".
