### ISSUE TITLE
CloudWatchMetricObserver.putMetricData swallows AmazonServiceException

### ISSUE THREAD

**Issue by fredshonorio** [Netflix/servo#410]
I'm not sure if this is was overlooked or an explicit decision (feel free to close this issue if so), but it made an issue with using the wrong credentials slightly hard to debug.

See:
https://github.com/Netflix/servo/blob/c190cd451ba651b80c8286c31651e56e91775e08/servo-aws/src/main/java/com/netflix/servo/publish/cloudwatch/CloudWatchMetricObserver.java#L205-L207

**Comment by alyssaBiasi** [comment]
Hey just wondering when a new version will be released with this change :slightly_smiling_face:

**Comment by brharrington** [comment]
@alyssaBiasi [0.12.17](https://github.com/Netflix/servo/releases/tag/v0.12.17) was just released with the change.
