### ISSUE TITLE
Memory leak suspect in BasicMonitorRegistry

### ISSUE THREAD

**Issue by marckamerbeek** [Netflix/servo#419]
Hi,

I'm running Neflix Zuul in Docker on Kubernetes. Once in a few days Zuul restarts on kubernetes due an out of memory. An analysis shows that its the Set of monitors in the com.netflix.servo.BasicMonitorRegistry that is growing. I really have no clue how this can grow.

Specs:
Spring cloud starter Zuul 1.3.1 in Spring Cloud version Dalston.SR1
Spring boot version 1.5.3
Spring cloud netflix core version: 1.3.1

Heap dump analysis shows the following:
![image](https://user-images.githubusercontent.com/7521474/27323306-6824fd9a-55a1-11e7-9f31-8ddda7e9c690.png)

Diving deeper: 
![image](https://user-images.githubusercontent.com/7521474/27323335-86dde486-55a1-11e7-98d9-f80ac38d4ab6.png)

And even deeper:
![image](https://user-images.githubusercontent.com/7521474/27323495-0cb9284a-55a2-11e7-92ae-9157c8315745.png)

Any idea how this can happen?  I can send you the heapdump on request (+300Mb).

**Comment by brharrington** [comment]
My guess something is just registering a lot of monitors. If you dump the contents of the registry does anything stand out?

**Comment by marckamerbeek** [comment]
Thanks for answering. Yesterday I disabled Servo with  -Dspring.metrics.servo.enabled=false. That seems to be working. No memory leak now. This morning I enabled it again in production to see what kind of monitors are registered with /manage/metrics. I made a snapshot and will compare this with the result after a few days. I'll keep you posted.

**Comment by marckamerbeek** [comment]
After one day running on production, the metrics shown in /manage/metrics is not increasing substantially. I got 133 metrices. Memory usage is increasing, so it looks like the memory leak is happening again.

**Comment by marckamerbeek** [comment]
Did some more investigation on the content of the hashmap that is growing. The hashmap is showing 1.2 million instances of AtomicLong:
![image](https://user-images.githubusercontent.com/7521474/27419907-9aac8390-5723-11e7-8748-f5f53788a3a8.png)

Following this AtomicLong Reference shows each time this trace:
![image](https://user-images.githubusercontent.com/7521474/27419950-d0d87e60-5723-11e7-9e11-849d0f31bd2b.png)

So it looks like it has something to do with the use of Netflix Eureka in Zuul.

**Comment by hxs8839** [comment]
I faced a similar issue with Servo on a long duration load test. Heap dumps showed that it primarily had the metrics from List<Metrics> in updateImpl() we were sending via the observer that was long delivered but still in heap. Added a finally block to explicitly nullify the List<Metrics> and other local objects created in the updateImpl method of the observer which seemed to help with those objects getting garbage collected

**Comment by marckamerbeek** [comment]
Thanks @hxs8839 for your comment. I finally removed Netflix Eureka(was planned) and the problem is gone now. I now use the kubernetes dns with loadbalancer to find my services. I don't have the time to investigate the combination Netflix Servo and Netflix Eureka and why its causing problems.

**Comment by brharrington** [comment]
@hxs8839 based on the memory profiles included in this ticket that sounds like a different problem. Feel free to submit a PR if you think it would help.

Looking at [NamedConnectionPool](https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/shared/NamedConnectionPool.java) in Eureka and the memory profiles above, it looks like something is creating NamedConnectionPool instances and not unregistering.

**Comment by hxs8839** [comment]
@brharrington agreed. Yeah I made the change for my custom observer, Working on if we can generalize it

**Comment by marckamerbeek** [comment]
@brharrington. I'm not in the position right to spend a lot of time on this. Hopefully somebody else can profit from this. Thanks anyway.

**Comment by sunl** [comment]
@marckamerbeek  please look at : https://github.com/spring-cloud/spring-cloud-netflix/issues/947

**Comment by yannxia** [comment]
i have same problem
![image](https://user-images.githubusercontent.com/6848593/34455623-0cad888c-edbe-11e7-8914-086c97e574f1.png)

hashmap has too many key
![image](https://user-images.githubusercontent.com/6848593/34455625-2af2cd3e-edbe-11e7-9052-fa12a99d3ccd.png)

version: com.netflix.servo:servo-core:0.10.1  by SpringBoot Dalston.SR4

**Comment by brharrington** [comment]
See the linked spring ticket (spring-cloud/spring-cloud-netflix#947), it seems like a bug in how spring is registering metrics.

**Comment by yannxia** [comment]
@brharrington  #947 not a prefect solution,  sometime our api-gateway don't konw how many queryparm in url, so the code will be

` this.restTemplate.postForEntity(url + "?" + requestVo.getQueryString(), formEntity, String.class).getBody()`

RestTemplate has no dynamic queryparm method, if use urlBuilder then question begin again

**Comment by wyzssw** [comment]
Disable ServoMetrics by add spring.metrics.servo.enabled=false to application.properties
