### ISSUE TITLE
Observer for InfluxDb

### ISSUE THREAD

**Issue by jeffbakerexpedia** [Netflix/servo#421]
We're interested in using Servo with InfluxDb, and noticed the https://github.com/PolymathicCoder/servo-influxdb observer written a couple of years ago. Was this  code ever considered for inclusion in https://github.com/Netflix/servo?

**Comment by mukteshkrmishra** [comment]
Yes. It was written last year, but we never raise a pull req in hystrix contrib repo.

**Comment by brharrington** [comment]
As far as I know it hasn't been brought up before. Most of our future efforts are going towards spectator (see [comparison page](http://netflix.github.io/spectator/en/latest/intro/servo-comparison/) for details) and there is an issue (Netflix/spectator#430) to add a registry type that would be easier to adapt to a variety of systems that support a basic http post.

There have been some debates in the past about the best model to support aspects that Netflix doesn't directly use. For example, should they be kept in separate repos or part of the main repo. Adding to the main repo aides discoverability and means they evolve and get tested together. The downside though is if we don't use it we aren't as interested in investing in the maintenance of those sub-projects. So unless the contributor continues to support it after the initial submission, then they tend to get stale. We had this problem with a graphite observer that was contributed. A separate repo makes the support story more clear. Not sure there was a firm conclusion though.
