### ISSUE TITLE
Booleans not changed into int values by MonitorRegistryMetricPoller

### ISSUE THREAD

**Issue by PeterOsudio** [Netflix/servo#427]
From the documentation on the wiki I understand that the poller is able to change booleans into 0/1 values. 
> The poller will try to match all values with simple numeric types. Boolean data will also be collected and recorded as a 1 if the value is true and 0 if the value is false.

Looking in my implementation and while debugging I see that my boolean values still end up in metrics as boolean values instead of integers. This makes that the metric is not published to Cloudwatch because CloudWatchMetricObserver checks for a numerical value.

Should I use a different poller, or am I missing something else? 

NB. It is fairly easy to extend MonitorRegistryMetricPoller and override the getValue() method, but since the docu is so explicit I wonder if I could do it without implementing a custom poller.

**Comment by brharrington** [comment]
I know that is something the [JmxMetricPoller] does, not sure if it was ever done anywhere else. @dmuino might have more context.

[JmxMetricPoller]: https://github.com/Netflix/servo/blob/master/servo-core/src/main/java/com/netflix/servo/publish/JmxMetricPoller.java#L255

**Comment by dmuino** [comment]
I'm afraid I don't have any more context. I was unaware of the fact that `JmxMetricPoller` converts booleans to numbers. Internally we don't use the `JmxMetricPoller`, and just ignore non-numeric values. My vote is to fix the documentation to reflect that fact.

**Comment by PeterOsudio** [comment]
I'm affraid that I have to change MonitorRegistryMetricPoller to also have this ability. We use it to monitor Hystrix (with the help of [hystrix-servo-metrics-publisher](https://github.com/Netflix/Hystrix/tree/2.0.x/hystrix-contrib/hystrix-servo-metrics-publisher) and the most important metric is isCircuitBreakerOpen, which is a boolean.

I will make a PR when I get it working.

**Comment by PeterOsudio** [comment]
PR created: https://github.com/Netflix/servo/pull/428 not sure why it is not linked automatically
