### ISSUE TITLE
AwsInjectableTag should be lazily initialised

### ISSUE THREAD

**Issue by dimas** [Netflix/servo#431]
Not all the tags can be resolved for all EC2 instances. For example machines in VPC may not have public hostname or ipv4 etc.
Because all the enum values are initialised together when class is loaded, that produces lots of warning in the log from all the processes.

Would be better if enum's `getValue()` thing did resolution when called for the first time (and cached the result of course). This way tags that are not actually used, won't cause any warnings.

**Comment by brharrington** [comment]
Not sure when we'll get to it, pull requests are welcome.
