### ISSUE TITLE
StepCounters loose increments when poll is behind schedule

### ISSUE THREAD

**Issue by cykl** [Netflix/servo#433]
I just ran into the following corner case and am wondering whether Servo behavior is assumed:
 
 - I use Spectactor with a ServoRegistry (thanks to spring-cloud-netflix)
 - Application does not define a `TaskScheduler` and thus use the default single threaded executor
 - Application uses another third-party hogging the thread (hello [spring-cloud-consul](https://github.com/spring-cloud/spring-cloud-consul/issues/146)!), leading to late executions of Spring Boot's `MetricsExporter` and thus of Servo's pollers. By late, I mean that the task runs about every two minutes rather than every 60 seconds.
 - I observe that increments performed during steps that are not pooled are lost

This is quite easy to reproduce with a test case:

```
  @Test
  public void increment_is_not_lost() {
    Counter c = newCounter("foo");
    clock.setWallTime(60_000);
    c.increment();
    clock.setWallTime(179_999);
    Assert.assertEquals(Iterables.get(c.measure(), 0).value(), 0.016, 0.001);
  }

  @Test
  public void increment_is_lost() {
    Counter c = newCounter("foo");
    clock.setWallTime(60_000);
    c.increment();
    clock.setWallTime(180_000);
    Assert.assertEquals(Iterables.get(c.measure(), 0).value(), 0, 0.001);
  }

```  

Looking at the code, it seems that implementation assumes that polling will never really lag and does not try handle stragglers gracefully. Theorically, a StepLong could return the delta between two effective polls, and StepCounter could compute the rate based on a real time delta rather than a target polling interval. Could you confirm that the current design is deliberate and that a sporadically incremented counter combined to a laggy poller is expected to loose increments ?

**Comment by dmuino** [comment]
We used to keep track of the last poll time, and we had a special case for missed polls, but we decided to simplify the behavior:

https://github.com/Netflix/servo/commit/29d77a41bde4cd04b61d46909043cc1bac4513d6#diff-2b45014017c4137b6080dc2c186ca63f

We used to return NaN instead of the rate based on the deltas though, but the major motivation was the significant reduction in the memory footprint of the class.

**Comment by brharrington** [comment]
> it seems that implementation assumes that polling will never really lag and does not try handle stragglers gracefully

Generally with telemetry at Netflix, we distinguish between operational and business use-cases. For operational use-cases the key question we are trying to answer is what is going on right now and we have SLAs around when data must be actionable. That is we have alerts and automated remediation based on the data that is coming in and we have to know when the data is complete and can be trusted so we can act on it. There has also been a push over time to reduce the mean-time to detect meaning we need to keep the SLA as tight as possible. So generally we do not want the operational data to lag or cover up that it is failing to meet the publishing SLA, but that does mean that it is more likely there will be some data loss.

For business intelligence use-cases the no data loss is a big concern, but our team is not focused on those use-cases.

**Comment by cykl** [comment]
Thank you both for your input. It makes sense. 

> Generally with telemetry at Netflix, we distinguish between operational and business use-cases. [...] So generally we do not want the operational data to lag or cover up that it is failing to meet the publishing SLA, but that does mean that it is more likely there will be some data loss. For business intelligence use-cases the no data loss is a big concern

My use of "straggler" was perhaps misleading. My use-case is not not a BI one. What led me to filling this issue was a feature team questioning me about the following graph (CW: 5mn period):

![5mn period](https://user-images.githubusercontent.com/1764725/33710092-c83b5890-db3f-11e7-9bdf-1ce06ebffbb8.png)

They were puzzled to only see 0s. "_Why a Counter would be reactived if there is no increment?_" Zooming to a 1mn period and throubleshooting their service I was able to explain them what is going on (thread poll is satured, some steps are not polled, data is lost, you will never know what the error rate was). 

![1mn period](https://user-images.githubusercontent.com/1764725/33710139-edf499fc-db3f-11e7-8628-64fe456e95aa.png)

However, they then asked "_Why would Servo discard missed steps rather than gracefully handle them by computing the rate over the observed polling period?_" I wanted to provide them first hand answer.


BTW, If Servo expects that polling must not be too delayed, which is reasonable, wouldn't it be useful to warn if late polling is observed? (IIRC HikariCP does something like that). I know how to fix their issue, but am afraid some other feature team does the same mistake. How do you prevent such broken config to reach production?
