### ISSUE TITLE
JmxMetricPoller: Trouble adding Tabular metrics

### ISSUE THREAD

**Issue by JashG** [Netflix/servo#453]
I am running into a bit of trouble publishing JMX metrics that store values using Java's TabularData class. This functionality is included in the `JmxMetricPoller` class:

```
private void addTabularMetrics(MetricFilter filter, List<Metric> metrics, TagList tags,
                                 String attrName, CompositeData obj) {
    Map<String, Object> values = new HashMap<>();
    // tabular composite data has a value called key and one called value
    values.put(obj.get("key").toString(), obj.get("value"));
    for (Map.Entry<String, Object> e : values.entrySet()) {
      final Tag compositeTag = Tags.newTag(COMPOSITE_PATH_KEY, e.getKey());
      final TagList newTags = getTagListWithAdditionalTag(tags, compositeTag);
      if (filter.matches(MonitorConfig.builder(attrName).withTags(newTags).build())) {
        addMetric(metrics, attrName, newTags, e.getValue());
      }
    }
  }
```

In a nutshell, a TabularData object can be thought of as serving the purpose of a JMX Attribute; it has a name and a value, where the value is stored as a CompositeData object. Unlike a typical attribute, which just stores a single value, a CompositeData object stores key-value pairs that represent as many values as you want.

I am seeking clarification on this snippet of code: 
`values.put(obj.get("key").toString(), obj.get("value"));`

 I imagine the `values` HashMap should be storing each of the key-value pairs in the CompositeData object? `obj.get()` retrieves the value associated with a particular key name stored in a CompositeData object. So if I have two keys named "time" and "place", `obj.get("time")` will give me the value associated with the key, time. Same for `obj.get("place")`.

Just wondering if anyone has run into this issue, or if I'm maybe misunderstanding this bit of code? I think I read somewhere that Netflix doesn't internally use JmxMetricPoller, but figured I'd ask anyway :)

**Comment by brharrington** [comment]
I'm not sure why it creates a map and loops there as it will only have iteration.

This code was originally for some polling use-cases based on the table types that we had use-cases for at the time. They were all essentially lists with two columns: `key` and `value`. So it needed to extract the value of the `key` column and map it to the value of the `value` column. For example, system properties are mapped into JMX in that way:

<img width="1194" alt="jmx" src="https://user-images.githubusercontent.com/1289028/43655837-087e9c9c-9705-11e8-9563-161d043d825c.png">

It sounds like you are trying to read something that has a different table structure. That is it has potentially many columns and the key is actually the column name. I don't think that would work as it is written today. Not sure how easy it would be to support as somehow the structure of the table would need to be understood for a given mbean. So there would need to be some configuration.

At Netflix we do not currently use the Servo JmxMetricPoller and in general Servo is in maintenance mode. We do have some use-cases for extracting data via JMX that are handled by the [spectator-ext-jvm](https://github.com/Netflix/spectator/tree/master/spectator-ext-jvm) library. It supports configurations for what data to fetch and how to map it in. Not sure if it would support the table formats at this time as the mapping has been mostly focused on use-cases we have. So we add to it as we have the need. That said, PRs are welcome if you have a suggestion for improving it.

**Comment by JashG** [comment]
Ah, understood! My case looks something like this:
![jmx](https://user-images.githubusercontent.com/37194352/43658977-7dbcc9c0-9728-11e8-9e50-979eeb5647a5.png)

Each row in the table is considered a key-value pair (i.e. "time" is the key and get("time") would be it's value, 332). The table itself is an instance of the CompositeData class. If I can suggest an improvement I will submit a PR.
